### ISSUE TITLE
建议：关于release

### ISSUE THREAD

**Issue by Ecalose** [kkevsekk1/AutoX#300]
其实action也可以相应上传打包后的apk到release的，或者appcenter也是个不错的选择

**Comment by LZX284** [comment]
@Ecalose 修改一下workflow应该就可以了吧，不过这个问题应该也只能由作者 @kkevsekk1 来解决，就看他是不是有这个意愿了……

**Comment by wangwang-code** [comment]
https://github.com/wangwang-code/AutoX/releases/tag/6.0.10 
```
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /home/runner/work/AutoX/AutoX/build/app/signed/app-dev-arm64-v8a-release-unsigned-signed.apk
```
很简单（也就失败了3次而已）
